name: Backup your GitHub repositories to Synology

on:
  workflow_dispatch:

env:
  
  # ==== Versions ====

  AZ_CLI_VERSION: 2.45.0

  # ==== General settings  ====

  GH_API: api.github.com

  # ==== repos ====:


  # ==== Secrets ====
  GHA_PAT_SYN: ${{ secrets.GHA_PAT_SYN }}


jobs:
  Backup:
    runs-on: ubuntu-latest
    steps:
    - name: Set Base environment variables
      run: |

        echo "LOCAL_IP=$(curl whatismyip.akamai.com)" >> $GITHUB_ENV
        echo "REP_API_URL=https://$GH_API:orgs/ORG/repos" >> $GITHUB_ENV
        echo "USR_API_URL=https://$GH_API/user" >> $GITHUB_ENV
        echo "GH_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV # "/github/workspace"

      shell: bash

    # Variables in the env map cannot be defined in terms of other variables in the map
    - name: Set dependent environment variables
      run: |

      shell: bash

    - name: Backup
      run: |

        gh_usr=($curl -H "Authorization: Bearer ${{ env.GHA_PAT }}" -H "Accept: application/vnd.github.v3+json" ${{ env.USR_API_URL }} | jq .login)
        # curl -X GET -u username:${{ env.GHA_PAT }} -H "Accept: application/vnd.github.v3+json" ${{ env.API_URL }}

        echo "checking all repos for User $gh_usr ..."

        # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
        echo "GITHUB_REPOSITORY=${{github.repository}}"
        echo "GITHUB_REPOSITORY_OWNER="${{github.repository.owner}}"

        echo "About to Backup repos using Scripts from  https://github.com/${{github.repository}} ..."

        curl -H "Authorization: Bearer ${{ env.GHA_PAT }}" -H "Accept: application/vnd.github.v3+json" ${{ env.REP_API_URL }}

        for repo in $(curl -H "Authorization: Bearer ${{ env.GHA_PAT }}" -H "Accept: application/vnd.github.v3+json" ${{ env.REP_API_URL }})
        do
          echo "Verifying repo $repo"
        done        

        echo "All repositories have been listed"

      shell: bash
      env:
        GHA_PAT: ${{ secrets.GHA_PAT_SYN }}

