name: Backup your GitHub repositories to Synology

on:
  workflow_dispatch:
    inputs:
      extra_repos:
        description: The List of extra repos as an Array of string
        required: false
        type: string
        default:  "'repo1' 'repo2'"

env:
  
  # /!\ Variables in the env map cannot be defined in terms of other variables in the map

  # ==== Versions ====

  AZ_CLI_VERSION: 2.45.0

  # ==== General settings  ====

  GH_API: api.github.com

  # ==== Secrets ====
  GHA_PAT_SYN: ${{ secrets.GHA_PAT_SYN }}


jobs:
  Backup:
    runs-on: ubuntu-latest
    steps:
    - name: Set Base environment variables
      run: |

        echo "LOCAL_IP=$(curl whatismyip.akamai.com)" >> $GITHUB_ENV
        echo "GH_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV # "/github/workspace"
        echo "EXTRA_REPOS=${{ inputs.extra_repos }}" >> $GITHUB_ENV

      shell: bash

    # Variables in the env map cannot be defined in terms of other variables in the map
    - name: Set dependent environment variables
      run: |

        USR_API_URL=https://${{ env.GH_API }}/user
        gh_usr=$(curl $USR_API_URL -H "Authorization: Bearer ${{ env.GHA_PAT }}" -H "Accept: application/vnd.github.v3+json" | jq -r '.login')
        # curl -X GET -u username:${{ env.GHA_PAT }} -H "Accept: application/vnd.github.v3+json" ${{ env.API_URL }}

        echo "checking all repos for User $gh_usr ..."
        echo "GH_USR=$gh_usr" >> $GITHUB_ENV

        # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
        echo "GITHUB_REPOSITORY=${{github.repository}}"
        echo "GITHUB_REPOSITORY=${{github.repository}}" >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY_OWNER="${{github.repository.owner}}
        echo "GITHUB_REPOSITORY_OWNER="${{github.repository.owner}} >> $GITHUB_ENV

        # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user
        echo "RPO_API_URL=https://$GH_API/user/repos" >> $GITHUB_ENV
        echo "USR_API_URL=https://$GH_API/users/$gh_usr/repos?per_page=100" >> $GITHUB_ENV #https://$GH_API/user"

      shell: bash
      env:
        GHA_PAT: ${{ secrets.GHA_PAT_SYN }}

    # Variables in the env map cannot be defined in terms of other variables in the map
    - name: Display environment variables
      run: |

        echo "LOCAL_IP=$LOCAL_IP
        echo "GH_USR=$GH_USR"
        echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
        echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
        echo "RPO_API_URL=$RPO_API_URL
        echo "USR_API_URL=$USR_API_URL
        echo "GH_WORKSPACE=$GH_WORKSPACE
        echo ""
        
        echo "Verifying repos:"
        echo ""
        for repo in ${{ env.EXTRA_REPOS }}
        do
          echo "$repo"
        done
        echo ""

      shell: bash

    - name: Backup
      run: |

        backup_dir=$(date +"%y%m%d")
        mkdir $backup_dir
        echo "created BackUp folder " $backup_dir

        echo "About to Backup repos using Scripts from  https://github.com/${{github.repository}} ..."

        # https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-organizations
        # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user
        # https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28
        curl --include --request GET  ${{ env.RPO_API_URL }} \
          -H "Authorization: Bearer ${{ env.GHA_PAT }}" -H "Accept: application/vnd.github.v3+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          | grep -i "link"

        repos=$(curl -H "Authorization: Bearer ${{ env.GHA_PAT }}" -H "Accept: application/vnd.github.v3+json" -H "X-GitHub-Api-Version: 2022-11-28"  ${{ env.RPO_API_URL }} | jq '.[] | .name' )
        
        
        #echo $repos
        #echo "$repos" | jq length
        numberOfRepos=($repos | jq length)
        echo "There are $numberOfRepos repos to BackUp"

        for i in {0..$numberOfRepos-1}
        do
          repo_name="$repos[i]"
          echo "$repo_name"
          echo ""
        done     

        echo "All repositories have been listed, now checking extra repos"

      shell: bash
      env:
        GHA_PAT: ${{ secrets.GHA_PAT_SYN }}

